/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityFeed: typeof import('./src/components/ActivityFeed.vue')['default']
    AddCardDialog: typeof import('./src/components/AddCardDialog.vue')['default']
    AddDomainDialog: typeof import('./src/components/AddDomainDialog.vue')['default']
    AppIcon: typeof import('./src/components/AppIcon.vue')['default']
    CentralShell: typeof import('./src/components/CentralShell.vue')['default']
    ChangeVersionDialog: typeof import('./src/components/ChangeVersionDialog.vue')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    DemoSwitch: typeof import('./src/components/DemoSwitch.vue')['default']
    DropSiteDialog: typeof import('./src/components/DropSiteDialog.vue')['default']
    MoveSiteDialog: typeof import('./src/components/MoveSiteDialog.vue')['default']
    NewSiteDialog: typeof import('./src/components/NewSiteDialog.vue')['default']
    OnboardingShell: typeof import('./src/components/OnboardingShell.vue')['default']
    ProviderRegionPicker: typeof import('./src/components/ProviderRegionPicker.vue')['default']
    ResizeDialog: typeof import('./src/components/ResizeDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerActions: typeof import('./src/components/ServerActions.vue')['default']
    ServerHealth: typeof import('./src/components/ServerHealth.vue')['default']
    ServerShell: typeof import('./src/components/ServerShell.vue')['default']
    SiteCard: typeof import('./src/components/SiteCard.vue')['default']
    WorldMap: typeof import('./src/components/WorldMap.vue')['default']
  }
}
