/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityFeed: typeof import('./src/components/ActivityFeed.vue')['default']
    AddCardDialog: typeof import('./src/components/AddCardDialog.vue')['default']
    AddDomainDialog: typeof import('./src/components/AddDomainDialog.vue')['default']
    Alert: typeof import('./src/components/Alert.vue')['default']
    AppIcon: typeof import('./src/components/AppIcon.vue')['default']
    CancelSubscriptionDialog: typeof import('./src/components/CancelSubscriptionDialog.vue')['default']
    CentralShell: typeof import('./src/components/CentralShell.vue')['default']
    ChangePlanDialog: typeof import('./src/components/ChangePlanDialog.vue')['default']
    ChangeVersionDialog: typeof import('./src/components/ChangeVersionDialog.vue')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    DemoSwitch: typeof import('./src/components/DemoSwitch.vue')['default']
    Disclosure: typeof import('./src/components/Disclosure.vue')['default']
    DropSiteDialog: typeof import('./src/components/DropSiteDialog.vue')['default']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    ErrorState: typeof import('./src/components/ErrorState.vue')['default']
    FcManageModal: typeof import('./src/components/FcManageModal.vue')['default']
    MigrationScheduledModal: typeof import('./src/components/MigrationScheduledModal.vue')['default']
    MoveSiteDialog: typeof import('./src/components/MoveSiteDialog.vue')['default']
    NewSiteDialog: typeof import('./src/components/NewSiteDialog.vue')['default']
    OnboardingShell: typeof import('./src/components/OnboardingShell.vue')['default']
    OtpInput: typeof import('./src/components/OtpInput.vue')['default']
    PaymentSetupDialog: typeof import('./src/components/PaymentSetupDialog.vue')['default']
    ProfileDialog: typeof import('./src/components/ProfileDialog.vue')['default']
    ProviderRegionPicker: typeof import('./src/components/ProviderRegionPicker.vue')['default']
    RailAccordion: typeof import('./src/components/RailAccordion.vue')['default']
    RazorpayCheckout: typeof import('./src/components/RazorpayCheckout.vue')['default']
    ReturnBar: typeof import('./src/components/ReturnBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerActions: typeof import('./src/components/ServerActions.vue')['default']
    ServerHealth: typeof import('./src/components/ServerHealth.vue')['default']
    ServerSettingsDialog: typeof import('./src/components/ServerSettingsDialog.vue')['default']
    ServerShell: typeof import('./src/components/ServerShell.vue')['default']
    SiteCard: typeof import('./src/components/SiteCard.vue')['default']
    SiteIcon: typeof import('./src/components/SiteIcon.vue')['default']
    SystemInfoDialog: typeof import('./src/components/SystemInfoDialog.vue')['default']
    UpdateServerDialog: typeof import('./src/components/UpdateServerDialog.vue')['default']
    WorldMap: typeof import('./src/components/WorldMap.vue')['default']
  }
}
